/**
 * Single source of truth for harness-workflow enums.
 *
 * These constants drive:
 *   - TypeScript types (via `as const` + `typeof X[number]`)
 *   - JSON schemas (regenerated by scripts/regen-schema.ts)
 *   - Markdown contracts (which must reference this file as source-of-truth)
 *
 * If you add / remove a value, run `npm run regen:schema` and commit the schema diff.
 */

export const MATCHER_TYPES = ['path_glob', 'git_remote_regex', 'file_exists'] as const;
export type MatcherType = (typeof MATCHER_TYPES)[number];

export const HARD_FLOOR_FLAGS = [
  'auto_push',
  'force_push',
  'destructive_ops',
  'auto_merge',
  'rewrite_history',
  'network_install',
] as const;
export type HardFloorFlag = (typeof HARD_FLOOR_FLAGS)[number];

export const TASK_TYPES = ['quick', 'bugfix', 'feature', 'refactor'] as const;
export type TaskType = (typeof TASK_TYPES)[number];

export const PUSH_RISK_LEVELS = ['low', 'medium', 'high'] as const;
export type PushRiskLevel = (typeof PUSH_RISK_LEVELS)[number];

export const AGGRESSION_MODES = ['conservative', 'standard', 'aggressive'] as const;
export type AggressionMode = (typeof AGGRESSION_MODES)[number];
