#!/bin/bash
# setup-harness.sh — One-time interactive setup for harness-v2.
#
# Prompts the user for their workflow preferences and writes the corresponding
# profile YAML files to ~/.claude/profiles/.  Never overwrites files without
# explicit confirmation; Ctrl-C leaves existing files untouched.
#
# Usage: ./setup-harness.sh

set -euo pipefail

# ─── Constants ────────────────────────────────────────────────────────────────

readonly PROFILES_DIR="${HOME}/.claude/profiles"
readonly HARNESS_YML="${PROFILES_DIR}/harness.yml"
readonly DEFAULT_YML="${PROFILES_DIR}/default.yml"
readonly COMPANY_TPL="${PROFILES_DIR}/company.yml.template"
readonly HOOK_SCRIPT="/Users/twelve/Music/myskills/harness-v2/hooks/context-monitor.sh"

# ANSI colours
if [[ -t 1 ]]; then
  BOLD="\033[1m"
  GREEN="\033[1;32m"
  YELLOW="\033[1;33m"
  CYAN="\033[1;36m"
  RED="\033[1;31m"
  RESET="\033[0m"
else
  BOLD="" GREEN="" YELLOW="" CYAN="" RED="" RESET=""
fi

# ─── Trap: graceful Ctrl-C ────────────────────────────────────────────────────
trap 'echo -e "\n${YELLOW}Setup interrupted. Existing files were not modified.${RESET}"; exit 1' INT TERM

# ─── Helpers ─────────────────────────────────────────────────────────────────

ask() {
  # ask <variable_name> <prompt>
  local var_name="${1}"
  local prompt="${2}"
  local answer
  echo -en "${CYAN}${prompt}${RESET} "
  read -r answer
  printf -v "${var_name}" '%s' "${answer}"
}

ask_yn() {
  # ask_yn <variable_name> <prompt> — returns "y" or "n"
  local var_name="${1}"
  local prompt="${2}"
  local answer
  while true; do
    echo -en "${CYAN}${prompt} [y/n]:${RESET} "
    read -r answer
    case "${answer}" in
      [Yy]) printf -v "${var_name}" 'y'; return ;;
      [Nn]) printf -v "${var_name}" 'n'; return ;;
      *) echo "  Please enter y or n." ;;
    esac
  done
}

section() {
  echo -e "\n${BOLD}── ${1} ──────────────────────────────────${RESET}"
}

check_file() {
  local path="${1}"
  if [[ -f "${path}" ]]; then
    echo -e "  ${GREEN}✓${RESET} ${path}"
  else
    echo -e "  ${RED}✗ missing:${RESET} ${path}"
  fi
}

ensure_profiles_dir() {
  if [[ ! -d "${PROFILES_DIR}" ]]; then
    echo -e "${YELLOW}Creating ${PROFILES_DIR} ...${RESET}"
    mkdir -p "${PROFILES_DIR}"
  fi
}

# ─── Start ────────────────────────────────────────────────────────────────────

echo -e "${BOLD}"
echo "╔══════════════════════════════════════════╗"
echo "║   harness-v2  —  Interactive Setup       ║"
echo "╚══════════════════════════════════════════╝"
echo -e "${RESET}"

# ─── 1. Pre-flight check ──────────────────────────────────────────────────────

section "Pre-flight check"
ensure_profiles_dir
check_file "${DEFAULT_YML}"
check_file "${HARNESS_YML}"
check_file "${COMPANY_TPL}"

# ─── 2. Development scenario ─────────────────────────────────────────────────

section "Primary development scenario"
echo "  1) Personal project  (Next.js / Go / Python)"
echo "  2) Company project"
echo "  3) Both"
echo ""
dev_scenario=""
while true; do
  ask dev_scenario "Choose [1/2/3]:"
  case "${dev_scenario}" in
    1|2|3) break ;;
    *) echo "  Enter 1, 2, or 3." ;;
  esac
done

# ─── 3. Push strategy ────────────────────────────────────────────────────────

section "Default push strategy (for personal projects)"
echo "  1) conservative — manual push only"
echo "  2) standard     — ask before pushing"
echo "  3) aggressive   — auto push"
echo ""
push_choice=""
while true; do
  ask push_choice "Choose [1/2/3]:"
  case "${push_choice}" in
    1) push_mode="conservative"; break ;;
    2) push_mode="standard";     break ;;
    3) push_mode="aggressive";   break ;;
    *) echo "  Enter 1, 2, or 3." ;;
  esac
done

# ─── 4. Company project details (if applicable) ───────────────────────────────

company_name=""
company_repo_path=""
company_remote_regex=""

if [[ "${dev_scenario}" == "2" || "${dev_scenario}" == "3" ]]; then
  section "Company project settings"
  ask company_name     "Company / workspace name (slug, e.g. acme):"
  ask company_repo_path "Local repo path (e.g. ~/work/acme-api):"
  ask company_remote_regex "git remote URL regex to match (e.g. github.com/acme):"
fi

# ─── 5. Optional features ────────────────────────────────────────────────────

section "Optional features"
enable_scanner="n"
ask_yn enable_scanner "Enable knowledge scanner (project-scanner)?"

enable_hook="n"
ask_yn enable_hook "Enable stop-hook context monitor?"

# ─── 6. Write harness.yml ────────────────────────────────────────────────────

section "Writing profile files"

write_harness_yml() {
  local scanner_enabled
  scanner_enabled="$([[ "${enable_scanner}" == "y" ]] && echo "true" || echo "false")"

  cat > "${HARNESS_YML}" <<YAML
# harness.yml — generated by setup-harness.sh on $(date +%Y-%m-%d)
name: harness
description: "harness-v2 default profile"
default_mode: ${push_mode}

features:
  project_scanner: ${scanner_enabled}
  context_monitor_hook: $([[ "${enable_hook}" == "y" ]] && echo "true" || echo "false")

task_types:
  quick:    harness-quick
  bugfix:   harness-bugfix
  feature:  harness-feature
  refactor: harness-refactor
YAML
  echo -e "  ${GREEN}✓${RESET} Written: ${HARNESS_YML}"
}

write_harness_yml

# ─── 7. Write company profile (if needed) ────────────────────────────────────

if [[ -n "${company_name}" ]]; then
  company_yml="${PROFILES_DIR}/company-${company_name}.yml"

  # Source template if it exists, otherwise create from scratch
  if [[ -f "${COMPANY_TPL}" ]]; then
    cp "${COMPANY_TPL}" "${company_yml}"
    # Patch the copied template with actual values using sed (portable)
    sed -i.bak \
      -e "s|__COMPANY_NAME__|${company_name}|g" \
      -e "s|__REPO_PATH__|${company_repo_path}|g" \
      -e "s|__REMOTE_REGEX__|${company_remote_regex}|g" \
      "${company_yml}" && rm -f "${company_yml}.bak"
  else
    # No template — generate a minimal company profile
    cat > "${company_yml}" <<YAML
# company-${company_name}.yml — generated by setup-harness.sh on $(date +%Y-%m-%d)
name: company-${company_name}
description: "Company workspace profile for ${company_name}"
default_mode: ${push_mode}

detection:
  priority: 10
  matchers:
    - type: repo_path
      pattern: "${company_repo_path}"
    - type: git_remote
      pattern: "${company_remote_regex}"

hard_floor:
  - auto_merge

task_types:
  quick:    harness-quick
  bugfix:   harness-bugfix
  feature:  harness-feature
  refactor: harness-refactor
YAML
  fi
  echo -e "  ${GREEN}✓${RESET} Written: ${company_yml}"
fi

# ─── 8. Hook registration instructions ───────────────────────────────────────

if [[ "${enable_hook}" == "y" ]]; then
  section "Stop-hook registration"
  echo -e "${YELLOW}Add the following to ~/.claude/settings.json (merge into existing JSON):${RESET}"
  echo ""
  cat <<'JSON'
{
  "hooks": {
    "Stop": [
      {
        "matcher": "",
        "hooks": [
          {
            "type": "command",
            "command": "/Users/twelve/Music/myskills/harness-v2/hooks/context-monitor.sh"
          }
        ]
      }
    ]
  }
}
JSON
  echo ""
  echo -e "Hook script location: ${CYAN}${HOOK_SCRIPT}${RESET}"
fi

# ─── 9. Summary ──────────────────────────────────────────────────────────────

section "Setup complete — summary"

echo -e "  ${GREEN}✓${RESET} Profile written : ${HARNESS_YML}"
[[ -n "${company_name}" ]] && \
  echo -e "  ${GREEN}✓${RESET} Company profile : ${PROFILES_DIR}/company-${company_name}.yml"
echo -e "  Push mode        : ${push_mode}"
echo -e "  Scanner          : ${enable_scanner}"
echo -e "  Context hook     : ${enable_hook}"

echo ""
echo -e "${BOLD}Next steps:${RESET}"
echo -e "  1. Start a new Claude session."
echo -e "  2. Activate harness: ${CYAN}/profile-entry${RESET}"
echo -e "  3. Dispatcher picks your task type automatically, or run:"
echo -e "     ${CYAN}/task-dispatcher${RESET}"
echo ""
echo -e "Validate any profile with:"
echo -e "  ${CYAN}/Users/twelve/Music/myskills/harness-v2/tools/harness-pack-test <profile.yml>${RESET}"
echo ""
